// app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Web3Provider } from "@/context/Web3Provider";
import { AdminSessionProvider } from "@/context/AdminSession"; // <-- Importieren

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Web3Provider>
          <AdminSessionProvider> {/* <-- Hier hinzufügen */}
            {children}
          </AdminSessionProvider>
        </Web3Provider>
      </body>
    </html>
  );
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};