/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPancakeRouter,
  IPancakeRouterInterface,
} from "../../../contracts/Treasury.sol/IPancakeRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "swapExactTokensForTokens",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPancakeRouter__factory {
  static readonly abi = _abi;
  static createInterface(): IPancakeRouterInterface {
    return new Interface(_abi) as IPancakeRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPancakeRouter {
    return new Contract(address, _abi, runner) as unknown as IPancakeRouter;
  }
}
